development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:59d03b64d1d4099d91028edf43671591@scat.redistogo.com:9541/
  channel_prefix: instatalk_production
